version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7.41
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306